# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Category", icon: "<i class='glyphicon glyphicon-th'></i>", label: Category }

    admin.recipes:
        class: AppBundle\Admin\RecipeAdmin
        arguments: [~, AppBundle\Entity\Recipe, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Recipes", icon: "<i class='glyphicon glyphicon-cutlery'></i>", label: Recipes }

    admin.ingredients:
        class: AppBundle\Admin\IngredientsAdmin
        arguments: [~, AppBundle\Entity\Ingredients, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Recipes", label: Ingredients }

    my.custom.user_provider:
        class:        MyBundle\Security\Core\User\MyFOSUBUserProvider
        arguments: ['@fos_user.user_manager', { facebook: facebook_id }]
